Repository rl-institut/super-repo, pull requests merged in 2023-08, with the labels that each got.

#43 Update RELEASE_PROCEDURE.md for Patch Release
  .github/ISSUE_TEMPLATE/issue_template_release.md
  .github/pull_request_template.md
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  mkdocs.yml
Labels: documentation, enhancement

#47 Add versioned documentation with mike #36
  .github/ISSUE_TEMPLATE/issue_template_bug.md
  .github/ISSUE_TEMPLATE/issue_template_feature.md
  .github/ISSUE_TEMPLATE/issue_template_release.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_release.md
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  docs/development/collaboration/citation.md
  docs/development/collaboration/contributing.md
  docs/development/collaboration/license.md
  docs/development/collaboration/users.md
  docs/development/documentation/index.md
  docs/development/release/index.md
  mkdocs.yml
Labels: enhancement

#49 Fix merge on production branch
  .github/ISSUE_TEMPLATE/issue_template_bug.md
  .github/ISSUE_TEMPLATE/issue_template_feature.md
  .github/ISSUE_TEMPLATE/issue_template_release.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_release.md
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  docs/development/collaboration/citation.md
  docs/development/collaboration/contributing.md
  docs/development/collaboration/license.md
  docs/development/collaboration/users.md
  docs/development/documentation/index.md
  docs/development/release/index.md
  mkdocs.yml
Labels: bug

#51 Release v0.2.0
  .github/PULL_REQUEST_TEMPLATE/pull_request_template_release.md
  .github/pull_request_template.md
  CHANGELOG.md
  CITATION.cff
  RELEASE_PROCEDURE.md
Labels: enhancement

#54 Improve the mike workflow
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  docs/css/extra.css
  docs/development/documentation/index.md
  docs/overrides/main.html
  mkdocs.yml
Labels: documentation, enhancement

#58 Update GitHub Action for develop branch
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  requirements.txt
Labels: part: docu :book:, type: enhancement :gear:, status: active :construction:, priority: high :zap:, part: github :octocat:

#56 Add pre-commit-hooks
  .github/ISSUE_TEMPLATE/issue_template_bug.md
  .github/ISSUE_TEMPLATE/issue_template_feature.md
  .github/ISSUE_TEMPLATE/issue_template_release.md
  .github/pull_request_template.md
  .pre-commit-config.yaml
  CHANGELOG.md
  CITATION.cff
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.rst
  RELEASE_PROCEDURE.md
  USERS.cff
  docs/code/code_example.md
  docs/code/style/index.md
  docs/css/extra.css
  docs/development/best-practice/test-driven-developement-workflow.md
  docs/development/collaboration/citation.md
  docs/development/collaboration/contributing.md
  docs/development/collaboration/users.md
  docs/development/documentation/index.md
  docs/development/git/pre-commit.md
  docs/index.md
  mkdocs.yml
  requirements.txt
  super_repo/example_google.py
Labels: part: docu :book:, part: backend :bricks:, type: feature :hammer_and_wrench:, status: completed :heavy_check_mark:, priority: high :zap:

#59 Add matrix chat
  CHANGELOG.md
  README.rst
  docs/development/collaboration/chat.md
  mkdocs.yml
Labels: type: feature :hammer_and_wrench:, status: completed :heavy_check_mark:, priority: high :zap:, part: community :earth_africa:

#60 Add community meetings #1
  CHANGELOG.md
  README.rst
  docs/development/collaboration/index.md
  docs/development/collaboration/meeting.md
  mkdocs.yml
Labels: type: enhancement :gear:, status: active :construction:, priority: high :zap:, part: community :earth_africa:

#62 Update the sections and merge subpages of the documentation
  .github/ISSUE_TEMPLATE/issue_template_bug.md
  .github/ISSUE_TEMPLATE/issue_template_feature.md
  .github/ISSUE_TEMPLATE/issue_template_release.md
  CHANGELOG.md
  CONTRIBUTING.md
  LICENSE.txt
  docs/development/collaboration/chat.md
  docs/development/collaboration/citation.md
  docs/development/collaboration/code_of_conduct.md
  docs/development/collaboration/contributing.md
  docs/development/collaboration/license.md
  docs/development/collaboration/license_and_citation.md
  docs/development/git/gitignore.md
  docs/development/git/index.md
  docs/development/git/pre-commit.md
  mkdocs.yml
Labels: part: docu :book:, type: enhancement :gear:, status: active :construction:, priority: high :zap:

#64 Add copyright notices with REUSE Software
  .github/pull_request_template.md
  .github/workflows/automated-testing.yml
  .github/workflows/gh-pages.yml
  .gitignore
  .pre-commit-config.yaml
  .reuse/dep5
  CHANGELOG.md
  CITATION.cff
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/CC0-1.0.txt
  LICENSES/MIT.txt
  README.rst
  RELEASE_PROCEDURE.md
  USERS.cff
  mkdocs.yml
  pyproject.toml
  requirements.txt
  super_repo/__init__.py
  super_repo/example_calculator.py
  super_repo/example_google.py
  tests/test_example.py
  tox.ini
Labels: part: backend :bricks:, type: feature :hammer_and_wrench:, status: completed :heavy_check_mark:, priority: high :zap:

#63 Add documentation for code style
  CHANGELOG.md
  docs/code/style/index.md
Labels: part: docu :book:, type: enhancement :gear:, status: completed :heavy_check_mark:, priority: high :zap:
